name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Pacman grafik dosyasını oluşturur
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Dosyayı varsayılan dala commit/push eder
      - name: Push Pacman SVG to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update pacman contribution graph"
          file_pattern: "dist/pacman.svg"
